SOV-439: WalletConnect
DistributedCollective/sovryn-onboard pull request #9
Opened 2022-09-15 10:55 UTC by creed-victor

https://sovryn.atlassian.net/browse/SOV-439

2022-09-17 13:17 UTC, tiltom requested changes

2022-09-17 13:17 UTC, tiltom commented on package.json
> +    "typescript": "^4.5.2"
Delete  `^`, see https://sovryn.monday.com/docs/2733202752?blockId=aebe8f4b-5e4a-4ef6-8967-503ce7a1bb30 .

2022-09-17 13:17 UTC, tiltom commented on packages/walletconnect/package.json
> +  }
Delete `^`, see https://sovryn.monday.com/docs/2733202752?blockId=aebe8f4b-5e4a-4ef6-8967-503ce7a1bb30 .

2022-09-17 13:17 UTC, tiltom commented on packages/walletconnect/src/index.ts
> +        // This is a cjs module and therefor depending on build tooling
```suggestion
        // This is a cjs module and therefore depending on build tooling
```

2022-09-19 11:14 UTC, tiltom requested changes

2022-09-19 11:32 UTC, tiltom approved these changes

2022-09-23 15:34 UTC, soulBit commented
Tested with Argent and Trust wallets on Android 12

Argent:
* connects successfully
* fails to sign message:
```
{
    "address": "0x9733b57e33046f4e1f8ed88f433c6364d126b4e0",
    "signer": "0x0d3ad0538Eb10E2207C5A8822427327fe3C7948B",
    "signature": "0x68994d682674b70d3dfc3d167cbf905a0f51d5846878ca1f67b7715dffc878300de89cd57a18eff506c45a5d85145a4998dce91e35e547ba90f401667702e61e1c"
}
```
* fails to sign typed data:
```
{
    "address": "0x9733b57e33046f4e1f8ed88f433c6364d126b4e0",
    "signer": "0x0d3ad0538Eb10E2207C5A8822427327fe3C7948B",
    "signature": "0x27d7016f0ff0bfbb9304764ca94d437653145b40fd9e25e2a1719ac95214da313c6f181ec2c1b6ca396a3d4d73c78a35040202cab16730c6c535a0bc7d2e51331b"
}
```

Trust wallet:
* does not connect

2022-09-23 15:35 UTC, soulBit requested changes
Tested with Argent and Trust wallets on Android 12

Argent:
* connects successfully
* fails to sign message:
```
{
    "address": "0x9733b57e33046f4e1f8ed88f433c6364d126b4e0",
    "signer": "0x0d3ad0538Eb10E2207C5A8822427327fe3C7948B",
    "signature": "0x68994d682674b70d3dfc3d167cbf905a0f51d5846878ca1f67b7715dffc878300de89cd57a18eff506c45a5d85145a4998dce91e35e547ba90f401667702e61e1c"
}
```

* fails to sign typed data:
```
{
    "address": "0x9733b57e33046f4e1f8ed88f433c6364d126b4e0",
    "signer": "0x0d3ad0538Eb10E2207C5A8822427327fe3C7948B",
    "signature": "0x27d7016f0ff0bfbb9304764ca94d437653145b40fd9e25e2a1719ac95214da313c6f181ec2c1b6ca396a3d4d73c78a35040202cab16730c6c535a0bc7d2e51331b"
}
```

Trust wallet:

* does not connect

2022-09-30 00:52 UTC, soulBit commented
Defiant, Metamask mobile working well - we need to define exactly which WalletConnect wallets work later, but approving for now to unblock development

2022-09-30 00:52 UTC, soulBit approved these changes

2022-09-30 00:52 UTC, merged